### ISSUE TITLE
CORS headers missing

### ISSUE THREAD

**Issue by mgamsjager** [hightechict/klootzakken.server.aspnetcore#4]
Can't access api due to CORS restructions.

**Comment by boekabart** [comment]
Will take a look, should be trivial to add with asp.net core.
btw same problem for SSO too?

**Comment by boekabart** [comment]
Fixed. Although 1 weird thing remains: the OPTIONS request returns 404 with the correct headers - no idea why! Can you @mgamsjager confirm whether this is an issue?

**Comment by boekabart** [comment]
Deployed on glueware.nl

**Comment by mgamsjager** [comment]
Tested with `http://www.glueware.nl/Klootzakken/kz/pin/create` and oddly enough no OPTIONS call is made. Beside that it seems to work.
